export const FAMED_PROGRAM = {
  institution:'FAMED',
  curriculum:'PPC 2018',
  activeSemester:'s5',
  semesters:[5, 6, 7, 8].map(number => ({
    id:`s${number}`,
    label:`S${number}`,
    available:number === 5,
  })),
  tracks:[
    {
      id:'cardio-pneumo',
      selectorLabel:'1ª metade',
      title:'Cardio + Pneumo',
      heading:'Cardiologia e Pneumologia',
      subtitle:'Módulo atual',
      description:'Cardiologia e Pneumologia da primeira metade do S5.',
      subjects:['Cardiologia', 'Pneumologia'],
      priority:true,
      status:'Cronogramas atuais carregados',
    },
    {
      id:'gastro-endocrino',
      selectorLabel:'2ª metade',
      title:'Gastro + Endócrino',
      heading:'Gastroenterologia e Endocrinologia',
      subtitle:'Segunda metade do semestre',
      description:'Gastroenterologia e Endocrinologia serão adicionadas quando o cronograma da segunda metade chegar.',
      subjects:['Gastroenterologia', 'Endocrinologia'],
      priority:false,
      status:'Planejado para depois',
    },
    {
      id:'abs-gestante-rn',
      selectorLabel:'ABS',
      title:'Gestante e RN',
      heading:'ABS da Gestante e do Recém-Nascido',
      subtitle:'Semestre inteiro',
      description:'ABS da Gestante e do Recém-Nascido acompanha as duas metades do S5.',
      subjects:['ABS'],
      priority:true,
      status:'Cronograma atual carregado',
    },
  ],
};
