export const JOURNEY_CURRICULUM_VERSION = '2026-05-20-direct-questions-v1';

export const JOURNEY_CURRICULUM = [
  {
    id: 'cardiologia',
    area: 'Cardiologia',
    topics: [
      'Hipertensão arterial sistêmica',
      'Dislipidemia e risco cardiovascular',
      'Dor torácica e síndrome coronariana aguda',
      'Insuficiência cardíaca',
      'Arritmias',
      'Valvopatias',
      'Miocardiopatias e miocardite',
      'Endocardite infecciosa',
      'Pericardite e doenças do pericárdio',
      'Tromboembolismo pulmonar e hipertensão pulmonar',
      'Síncope',
      'Parada cardiorrespiratória e suporte avançado',
    ],
  },
  {
    id: 'pneumologia',
    area: 'Pneumologia',
    topics: [
      'Asma',
      'DPOC',
      'Pneumonia',
      'Tuberculose pulmonar',
      'Derrame pleural',
      'Pneumotórax',
      'Tromboembolismo pulmonar',
      'Insuficiência respiratória',
      'Gasometria e distúrbios ácido-base',
      'Doenças intersticiais pulmonares',
      'Câncer de pulmão',
      'Nódulo pulmonar',
      'Apneia obstrutiva do sono',
    ],
  },
  {
    id: 'gastro-hepato',
    area: 'Gastroenterologia e Hepatologia',
    topics: [
      'Dor abdominal e abdome agudo',
      'Doença do refluxo gastroesofágico',
      'Dispepsia e doença ulcerosa péptica',
      'Hemorragia digestiva alta',
      'Hemorragia digestiva baixa',
      'Diarreia aguda e crônica',
      'Doenças inflamatórias intestinais',
      'Síndrome do intestino irritável',
      'Pancreatite aguda e crônica',
      'Colelitíase, colecistite e colangite',
      'Hepatites virais',
      'Cirrose e suas complicações',
      'Icterícia e colestase',
      'Doença hepática gordurosa',
      'Câncer colorretal e rastreamento',
    ],
  },
  {
    id: 'nefrologia',
    area: 'Nefrologia',
    topics: [
      'Injúria renal aguda',
      'Doença renal crônica',
      'Síndrome nefrítica',
      'Síndrome nefrótica',
      'Glomerulonefrites',
      'Distúrbios do potássio',
      'Distúrbios do sódio',
      'Distúrbios do cálcio, fósforo e magnésio',
      'Acidose e alcalose metabólica',
      'Infecção urinária alta e baixa',
      'Nefrolitíase',
      'Hipertensão secundária renal',
      'Terapia renal substitutiva e indicações de diálise',
      'Anemia e distúrbio mineral ósseo na DRC',
    ],
  },
  {
    id: 'endocrinologia',
    area: 'Endocrinologia',
    topics: [
      'Diabetes mellitus tipo 1 e tipo 2',
      'Complicações agudas do diabetes',
      'Complicações crônicas do diabetes',
      'Obesidade e síndrome metabólica',
      'Hipotireoidismo',
      'Hipertireoidismo',
      'Nódulo tireoidiano e câncer de tireoide',
      'Tireoidites',
      'Distúrbios da adrenal',
      'Síndrome de Cushing',
      'Insuficiência adrenal',
      'Hiperaldosteronismo',
      'Distúrbios da hipófise',
      'Osteoporose',
      'Dislipidemia',
    ],
  },
  {
    id: 'infectologia',
    area: 'Infectologia',
    topics: [
      'Sepse e choque séptico',
      'Antibióticos e espectro antimicrobiano',
      'Infecções de vias aéreas',
      'Pneumonia',
      'Infecção urinária',
      'Infecções de pele e partes moles',
      'Meningite e encefalite',
      'Endocardite infecciosa',
      'Tuberculose',
      'HIV e infecções oportunistas',
      'Hepatites virais',
      'Dengue, chikungunya e zika',
      'Malária',
      'Leptospirose',
      'Febre amarela',
      'Infecções sexualmente transmissíveis',
      'Neutropenia febril',
      'Infecção relacionada a dispositivos e cateteres',
    ],
  },
  {
    id: 'neurologia',
    area: 'Neurologia',
    topics: [
      'Cefaleias primárias',
      'Cefaleia secundária e sinais de alarme',
      'AVC isquêmico',
      'AVC hemorrágico',
      'Crises epilépticas e epilepsia',
      'Estado de mal epiléptico',
      'Alteração do nível de consciência e coma',
      'Tontura e vertigem',
      'Síncope neurológica e diagnósticos diferenciais',
      'Demências',
      'Doença de Parkinson e parkinsonismos',
      'Neuropatias periféricas',
      'Síndrome de Guillain-Barré',
      'Esclerose múltipla',
      'Miastenia gravis',
      'Meningite e encefalite',
    ],
  },
  {
    id: 'hematologia',
    area: 'Hematologia',
    topics: [
      'Anemia ferropriva',
      'Anemias megaloblásticas',
      'Anemias hemolíticas',
      'Anemia da doença crônica',
      'Policitemias',
      'Plaquetopenias',
      'Distúrbios de coagulação',
      'Trombose venosa e trombofilias',
      'Anticoagulação',
      'Leucemias agudas e crônicas',
      'Linfomas',
      'Mieloma múltiplo',
      'Síndrome de lise tumoral',
      'Neutropenia febril',
      'Transfusão e reações transfusionais',
    ],
  },
  {
    id: 'reumatologia',
    area: 'Reumatologia',
    topics: [
      'Artrite reumatoide',
      'Osteoartrite',
      'Gota e pseudogota',
      'Lúpus eritematoso sistêmico',
      'Síndrome antifosfolípide',
      'Espondiloartrites',
      'Vasculites',
      'Polimialgia reumática e arterite temporal',
      'Miopatias inflamatórias',
      'Esclerose sistêmica',
      'Síndrome de Sjögren',
      'Fibromialgia',
      'Monoartrite aguda',
      'Dor lombar inflamatória',
    ],
  },
  {
    id: 'dermatologia',
    area: 'Dermatologia',
    topics: [
      'Lesões elementares e semiologia dermatológica',
      'Dermatites e eczemas',
      'Psoríase',
      'Acne e rosácea',
      'Urticária e angioedema',
      'Infecções bacterianas da pele',
      'Micoses superficiais',
      'Infecções virais da pele',
      'Escabiose e pediculose',
      'Hanseníase',
      'Lesões pigmentadas e melanoma',
      'Carcinoma basocelular e espinocelular',
      'Farmacodermias',
      'Doenças bolhosas',
      'Úlceras cutâneas',
    ],
  },
  {
    id: 'gineco-obstetricia',
    area: 'Ginecologia e Obstetrícia',
    topics: [
      'Pré-natal de baixo risco',
      'Doenças hipertensivas da gestação',
      'Diabetes gestacional',
      'Sangramento da primeira metade da gestação',
      'Sangramento da segunda metade da gestação',
      'Trabalho de parto e parto',
      'Puerpério',
      'Infecções na gestação',
      'Sífilis, HIV e hepatites na gestação',
      'Contracepção',
      'Sangramento uterino anormal',
      'Amenorreia',
      'Síndrome dos ovários policísticos',
      'Endometriose',
      'Miomatose uterina',
      'Infecções ginecológicas e DIP',
      'Climatério e menopausa',
      'Câncer de colo uterino',
      'Câncer de mama',
      'Câncer de ovário e endométrio',
    ],
  },
  {
    id: 'pediatria',
    area: 'Pediatria',
    topics: [
      'Crescimento e desenvolvimento',
      'Aleitamento materno',
      'Alimentação complementar',
      'Calendário vacinal',
      'Febre sem sinais localizatórios',
      'Infecções de vias aéreas',
      'Bronquiolite',
      'Pneumonia na criança',
      'Asma na criança',
      'Diarreia e desidratação',
      'Dor abdominal na criança',
      'Infecção urinária na criança',
      'Convulsão febril',
      'Sepse pediátrica',
      'Reanimação neonatal',
      'Icterícia neonatal',
      'Distúrbios respiratórios do recém-nascido',
      'Prematuridade',
      'Maus-tratos e negligência',
      'Emergências pediátricas',
    ],
  },
  {
    id: 'cirurgia',
    area: 'Cirurgia',
    topics: [
      'Abdome agudo',
      'Apendicite aguda',
      'Colecistite e colangite',
      'Pancreatite aguda cirúrgica',
      'Obstrução intestinal',
      'Hérnias',
      'Trauma abdominal',
      'Trauma torácico',
      'Atendimento inicial ao trauma',
      'Choque hemorrágico',
      'Queimaduras',
      'Infecção de sítio cirúrgico',
      'Cicatrização e cuidados com feridas',
      'Avaliação pré-operatória',
      'Complicações pós-operatórias',
      'Profilaxia de tromboembolismo venoso',
      'Cirurgia bariátrica',
      'Câncer colorretal cirúrgico',
    ],
  },
  {
    id: 'ortopedia',
    area: 'Ortopedia',
    topics: [
      'Fraturas e luxações',
      'Imobilização inicial',
      'Dor lombar mecânica',
      'Lombalgia com sinais de alarme',
      'Cervicalgia',
      'Osteoartrite',
      'Lesões ligamentares do joelho',
      'Dor no ombro',
      'Síndrome do túnel do carpo',
      'Osteomielite',
      'Artrite séptica',
      'Trauma de coluna',
      'Trauma de quadril',
      'Pé diabético e amputações',
      'Osteoporose e fratura por fragilidade',
    ],
  },
  {
    id: 'psiquiatria',
    area: 'Psiquiatria',
    topics: [
      'Depressão',
      'Risco suicida',
      'Transtornos de ansiedade',
      'Transtorno bipolar',
      'Psicose e esquizofrenia',
      'Agitação psicomotora',
      'Delirium',
      'Transtornos por uso de álcool',
      'Abstinência alcoólica',
      'Transtornos por outras substâncias',
      'Transtornos alimentares',
      'Transtornos de personalidade',
      'Insônia',
      'Psicofármacos e efeitos adversos',
      'Emergências psiquiátricas',
    ],
  },
  {
    id: 'intensiva-emergencias',
    area: 'Medicina Intensiva e Emergências',
    topics: [
      'Avaliação inicial do paciente grave',
      'Choque',
      'Sepse e choque séptico',
      'Insuficiência respiratória aguda',
      'Via aérea e ventilação',
      'Parada cardiorrespiratória',
      'Rebaixamento do nível de consciência',
      'Dor torácica na emergência',
      'Dispneia na emergência',
      'Abdome agudo na emergência',
      'Anafilaxia',
      'Intoxicações exógenas',
      'Distúrbios hidroeletrolíticos graves',
      'Emergências hipertensivas',
      'Emergências diabéticas',
      'Politrauma',
      'Queimaduras',
      'Sedação, analgesia e delirium em paciente crítico',
    ],
  },
  {
    id: 'oncologia',
    area: 'Oncologia',
    topics: [
      'Princípios gerais de oncologia',
      'Síndromes paraneoplásicas',
      'Emergências oncológicas',
      'Síndrome de lise tumoral',
      'Compressão medular',
      'Hipercalcemia da malignidade',
      'Neutropenia febril',
      'Câncer de mama',
      'Câncer de pulmão',
      'Câncer colorretal',
      'Câncer de próstata',
      'Câncer gástrico',
      'Câncer de colo uterino',
      'Cuidados paliativos',
      'Controle de dor oncológica',
    ],
  },
  {
    id: 'urologia',
    area: 'Urologia',
    topics: [
      'Hiperplasia prostática benigna',
      'Câncer de próstata',
      'Prostatite',
      'Litíase urinária',
      'Hematúria',
      'Infecção urinária complicada',
      'Retenção urinária aguda',
      'Escroto agudo',
      'Torção testicular',
      'Epididimite',
      'Disfunção erétil',
      'Incontinência urinária',
      'Trauma urológico',
    ],
  },
  {
    id: 'otorrinolaringologia',
    area: 'Otorrinolaringologia',
    topics: [
      'Otite média aguda',
      'Otite externa',
      'Rinossinusite',
      'Faringoamigdalite',
      'Epistaxe',
      'Vertigem periférica',
      'Hipoacusia',
      'Corpo estranho em vias aéreas superiores',
      'Abscessos cervicais e peritonsilar',
      'Rouquidão e disfonia',
      'Tumores de cabeça e pescoço',
    ],
  },
  {
    id: 'oftalmologia',
    area: 'Oftalmologia',
    topics: [
      'Olho vermelho',
      'Conjuntivites',
      'Ceratite',
      'Uveíte',
      'Glaucoma agudo',
      'Catarata',
      'Retinopatia diabética',
      'Retinopatia hipertensiva',
      'Descolamento de retina',
      'Perda visual súbita',
      'Trauma ocular',
      'Corpo estranho ocular',
      'Erros refracionais',
      'Fundoscopia e achados básicos',
    ],
  },
];

export const getCurriculumStats = () => {
  const topics = JOURNEY_CURRICULUM.reduce((sum, area) => sum + area.topics.length, 0);
  return { areas: JOURNEY_CURRICULUM.length, topics };
};

const normalize = (value) => String(value || '')
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '')
  .toLowerCase();

const priorityScore = ({ area, topic, topicIndex = 0 }) => {
  const text = normalize(`${area} ${topic}`);
  let score = 40 - Math.min(topicIndex, 20);

  [
    ['parada cardiorrespiratoria', 220],
    ['choque', 210],
    ['sepse', 205],
    ['avaliacao inicial do paciente grave', 200],
    ['via aerea', 195],
    ['insuficiencia respiratoria aguda', 192],
    ['dor toracica', 190],
    ['sindrome coronariana aguda', 188],
    ['avc', 185],
    ['rebaixamento', 180],
    ['coma', 178],
    ['dispneia', 176],
    ['abdome agudo', 174],
    ['anafilaxia', 172],
    ['emergencias diabeticas', 170],
    ['disturbios hidroeletroliticos graves', 168],
    ['emergencias hipertensivas', 166],
    ['politrauma', 164],
    ['queimaduras', 162],
    ['meningite', 160],
    ['encefalite', 158],
    ['neutropenia febril', 156],
    ['diabetes mellitus', 150],
    ['hipertensao arterial', 148],
    ['pneumonia', 146],
    ['asma', 144],
    ['dpoc', 142],
    ['infeccao urinaria', 140],
    ['injuria renal aguda', 138],
    ['doenca renal cronica', 136],
    ['insuficiencia cardiaca', 134],
    ['arritmias', 132],
    ['antibioticos', 130],
    ['anticoagulacao', 128],
    ['anemia', 126],
    ['hemorragia digestiva', 124],
    ['sangramento', 122],
    ['pre-natal', 120],
    ['doencas hipertensivas da gestacao', 118],
    ['risco suicida', 116],
    ['delirium', 114],
    ['convulsao', 112],
    ['crises epilepticas', 110],
    ['febre', 108],
    ['calendario vacinal', 106],
    ['aleitamento', 104],
    ['diarreia', 102],
    ['dor abdominal', 100],
    ['hipotireoidismo', 96],
    ['hipertireoidismo', 94],
    ['tuberculose', 92],
    ['hiv', 90],
    ['hepatites virais', 88],
    ['cirrose', 86],
    ['avaliação pre-operatoria', 84],
    ['avaliacao pre-operatoria', 84],
    ['fraturas', 82],
    ['olho vermelho', 80],
    ['descolamento de retina', 79],
    ['perda visual subita', 78],
    ['trauma ocular', 77],
    ['glaucoma agudo', 76],
    ['torcao testicular', 76],
    ['escroto agudo', 75],
    ['retencao urinaria aguda', 74],
    ['hematúria', 73],
    ['hematuria', 73],
    ['litiase', 72],
    ['epistaxe', 72],
    ['corpo estranho', 71],
    ['abscessos cervicais', 70],
    ['faringoamigdalite', 69],
    ['rinossinusite', 68],
    ['otite media', 67],
    ['vertigem periferica', 66],
    ['farmacodermias', 66],
    ['urticaria', 65],
    ['angioedema', 65],
    ['hanseniase', 64],
    ['infeccoes bacterianas da pele', 63],
    ['micoses', 62],
    ['ulceras cutaneas', 61],
    ['monoartrite aguda', 74],
    ['artrite septica', 74],
    ['gota', 64],
    ['lupus', 63],
    ['vasculites', 62],
    ['artrite reumatoide', 60],
    ['sindrome antifosfolipide', 59],
    ['depressao', 72],
    ['agitacao psicomotora', 71],
    ['abstinencia alcoolica', 70],
    ['psicose', 69],
    ['esquizofrenia', 69],
    ['transtorno bipolar', 66],
    ['ansiedade', 62],
    ['infeccoes de vias aereas', 78],
    ['bronquiolite', 76],
    ['diarreia e desidratacao', 74],
    ['reanimação neonatal', 84],
    ['reanimacao neonatal', 84],
    ['ictericia neonatal', 60],
    ['prematuridade', 58],
    ['diabetes gestacional', 78],
    ['sifilis', 76],
    ['contracepcao', 60],
    ['cancer de colo', 58],
    ['cancer de mama', 56],
    ['sindrome nefrótica', 70],
    ['sindrome nefrotica', 70],
    ['sindrome nefritica', 70],
    ['disturbios do potassio', 86],
    ['disturbios do sodio', 85],
    ['acidose', 84],
    ['alcalose', 84],
    ['glomerulonefrites', 66],
    ['nefrolitiase', 64],
    ['hipotensao', 80],
    ['tromboembolismo pulmonar', 152],
    ['derrame pleural', 88],
    ['pneumotorax', 130],
    ['gasometria', 122],
    ['doenca do refluxo', 58],
    ['dispepsia', 57],
    ['doenca ulcerosa', 70],
    ['pancreatite', 110],
    ['colecistite', 104],
    ['colangite', 108],
    ['ictericia', 76],
    ['colestase', 76],
    ['acidente vascular cerebral', 185],
  ].forEach(([needle, weight]) => {
    if (text.includes(needle)) score = Math.max(score, weight);
  });

  if (text.includes('emergenc')) score += 28;
  if (text.includes('agud')) score += 18;
  if (text.includes('complicacoes')) score += 8;
  if (text.includes('cancer') || text.includes('tumor')) score -= 18;
  if (text.includes('rastreamento')) score -= 8;
  if (text.includes('cronica') || text.includes('cronico')) score -= 4;

  return score;
};

export const getOrderedTopicRefs = () => {
  const refs = [];
  JOURNEY_CURRICULUM.forEach((area, areaIndex) => {
    area.topics.forEach((topic, topicIndex) => {
      refs.push({
        areaId: area.id,
        area: area.area,
        topic,
        areaIndex,
        topicIndex,
        priority: priorityScore({ area: area.area, topic, topicIndex }),
      });
    });
  });
  return refs
    .sort((a, b) => (b.priority - a.priority) || (a.topicIndex - b.topicIndex) || (a.areaIndex - b.areaIndex))
    .map((item, globalIndex) => ({ ...item, globalIndex }));
};

export const getTopicRefByIndex = (index = 0) => getOrderedTopicRefs()[index] || null;
